services:
  backend:
    image: hmthu30/ccs-backend:latest
    container_name: rust-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data/db:/app/data/db
      - ./data/images:/app/data/images
    environment:
      - DATABASE_URL=sqlite:/app/data/db/database.db
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080

  frontend:
    image: hmthu30/ccs-frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      # Use a direct path to the file in the same directory
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend